### PR TITLE
Add command to open terminal with OC CLI

### PR DESCRIPTION
**Pull request by evidolob**
PR add `Open developer terminal` copied from tray-app:

https://user-images.githubusercontent.com/929743/230340340-a684e08f-daf6-4c01-a364-049f420125ab.mov

### CODE REVIEW

**Comment by deboer-tim** [comment]
Nice addition!

**Comment by slemeur** [comment]
I think we purposely did integrate the terminal in Podman Desktop, in favor of opening a system terminal, to get a nicer integration.

**Comment by evidolob** [comment]
> I think we purposely did integrate the terminal in Podman Desktop, in favor of opening a system terminal, to get a nicer integration.

@slemeur You are, but you not expose terminal to extension API, so I cannot use it.

**Comment by deboer-tim** [comment]
Even here I think there's a balance. I really like the embedded terminals for containers, because they're ephemeral, there are lots of them, and when I need them I just want to click in and out. But when I want to use podman cli, I prefer the Mac terminal.

As Yehven says we have no API, and no design for where a terminal like this would fit in the UI. It would be good to have that as an option some day, but I'd still want preferences or ability to open external.

**Comment by gbraad** [comment]
The 'external' terminal can also pick up user preferences that an in-app terminal mostly can't. I consider those for quick one-off commands.

**Review by gbraad — APPROVED** [review]

**Pull request merged**
