### PR TITLE
chore(test): adding playwright e2e test

### PR DESCRIPTION
**Pull request by danivilla9**
Fixes issue #313. This PR introduces E2E tests using Playwright

In order to test:
1-Clone the podman-desktop repository
2-Go to podman-desktop folder
3-Execute `pnpm install`
4-Execute `pnpm test:e2e:build`
6-Set environment variable executing: `export PODMAN_DESKTOP_ARGS="/path/to/podman-desktop"`
7-Go to crc-extension folder
8-Execute `yarn install` 
8-Execute `yarn test:e2e `

*Remember that you have to use the latest version of @podman-desktop/tests-playwright in order to execute the tests

### CODE REVIEW

**Review by dgolovin — COMMENTED** [review]
Works for me, but I leave the approval to @odockal.

Description for the PR should be updated:
1. (2,3,4) should be updates to call pnpm from root of the podman-desktop
2. use yarn for the extension, because it is not migrated to pnpm yet.

**Review by odockal — APPROVED** [review]

**Comment by odockal** [comment]
@danivilla9 Can you please try also run the tests on the windows? you can use this workflow: https://github.com/containers/podman-desktop-e2e/actions/workflows/desktop-e2e-test-job-windows.yaml.

**Review by odockal — CHANGES_REQUESTED** [review]
We found out after discussion that we also need to add a test for a crc-extension dependency - Red Hat Authentication. So to check the presence of RH SSO once the OpenShift Local is installed and its state should be part of e2e tests.

We also encountered a bug. Which will be reported. We might consider to eventually add a test to cover this bug in another issue. @danivilla9 ^^

**Review by odockal — APPROVED** [review]

**Comment by odockal** [comment]
@danivilla9 please resolve the conflicts so we can merge the PR.

**Pull request merged**
