### PR TITLE
sync crc and extension preferences

### PR DESCRIPTION
**Pull request by evidolob**
This PR brings synchronisation of the preferences/configuration between crc-extension and crc CLI.

On extension start we reed configuration of crc CLI and update extension preferences.
When user change extension preference from UI, we check that crc configuration is not change, if it changed we ask user what to do.

Demo:

https://user-images.githubusercontent.com/929743/228148052-4134454a-f86f-45ec-84de-ed7ed4998ca1.mp4

### CODE REVIEW

**Comment by evidolob** [comment]
@gbraad I'm not super happy with that dialog message, we need to ask user what we should do if some preference was changed outside of PD UI.

**Comment by gbraad** [comment]
Slightly off-topic, but can we change the settings prefix to match the productname? 
image

`OpenShift-Local`

**Comment by gbraad** [comment]
@evidolob I am also not super happy... but honestly not sure what would be better. Ideally we would have the PD UI update the value as it sees the value has changed for crc, but either we use events to sent this back to the extension, ... or have to resort to what you do; conflict detection.

**Comment by evidolob** [comment]
Done:
Screenshot 2023-03-28 at 09 59 21

**Review by gbraad — APPROVED** [review]

**Comment by gbraad** [comment]
@evidolob let's look at this after we have a little bit more API and UI. I think this might also need some work on the daemon-side.

**Pull request merged**
