### PR TITLE
Add preset info to telemetry:crc.start

### LINKED ISSUE #155: Telemetry should include preset
The telemetry events for start, stop, commands do not include which preset is used. It would be good to log whether MicroShift or OpenShift Local is being used so we can prioritize between the two or understand when (e.g.) a behaviour or error is prevalent in one vs the other.

### PR DESCRIPTION
**Pull request by gbraad**
Fixes #155

### CODE REVIEW

**Comment by gbraad** [comment]
Seriously, I hate the linter:

```diff
-      preset: crcStatus.status.Preset
+      preset: crcStatus.status.Preset,
```

WHY?!?!?!?

**Comment by gbraad** [comment]
Oh no, wait... running:

```
$ npx prettier -w src/*.ts
```

results in:

```diff
-  telemetryLogger.logUsage('crc.start',
-    {
-      preset: crcStatus.status.Preset,
-    });
+  telemetryLogger.logUsage('crc.start', {
+    preset: crcStatus.status.Preset,
+  });
```

Which means `npm run lint:fix` was even wrong???

**Comment by gbraad** [comment]
@crc-org/crc-extension-team @jeffmaury @dgolovin Hope anyone can take a look.

**Review by deboer-tim — APPROVED** [review]

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
